---
- name: Install and configure neutron
  hosts: azure
  vars: 
    node_version: 12.16.1
    node_path: "/root/.nvm/versions/node/v{{node_version}}/bin"
  become: yes
  
  vars_files:
    - defaults/main.yml
  roles:
    - role: geerlingguy.mysql
    - role: geerlingguy.apache

  tasks:
    - name: Install java
      include: tasks/java.yml

    - name: Install node
      include: tasks/node.yml
   
    - name: Backend configuration
      include: tasks/backend.yml
    
    - name: Frontend configuration
      include: tasks/web.yml
  
    - name: install nginx
      include: tasks/nginx.yml
