---
- name: Install nginx
  apt:
    name: nginx
    state: present

- name: Nginx Configuration
  ansible.builtin.copy:
    src: /home/ubuntu/ansible-neutron/config/nginx.conf
    dest: /etc/nginx/nginx.conf
    user: root
    group: root
    mode: '0644'

- name: Restart NGiNX
  service:
    name: nginx
    state: restarted
